name: sql-test-action
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run:
          apt-get update
          apt-get install --yes --no-install-recommends postgresql-client
          sudo apt-get install postgresql-server-dev-all
          pip3 install psycopg2-binary
          python src/files/_test.py
        env:
      - name: export index