name: sql-test-action
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: update apt
        run: |
          sudo apt update
          sudo apt install postgresql postgresql-contrib
      - name: start pgsql
        run: |
          sudo systemctl start postgresql.service
          service postgresql status
          sudo -u postgres psql
      - name: create db
        run:
          sudo -u postgres psql < obce.sql
      - name: install psycopg2 library
        run:
          pip3 install psycopg2-binary
      - name: execute py script 2
        run:
          python _test.py