name: sql-test-action
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: update apt
        run:
          sudo apt update
      - name: install pg contrib
        run:
          sudo apt install postgresql postgresql-contrib
      - name: start sql service
        run:
          sudo systemctl start postgresql.service
      - name: install pg client
        run:
          sudo apt-get install --yes --no-install-recommends postgresql-client
      - name: install psycopg2 library
        run:
          pip3 install psycopg2-binary
      - name: execute py script 2
        run:
          python /src/_test.py